--- 
title: "Data Analysis: R Markdown"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
biblio-style: apalike
link-citations: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, comment = NA, out.width = '65%', fig.align = "center", fig.pos = 'H')
library(ggplot2)
library(dplyr)
library(moderndive)
library(gapminder)
library(skimr)
library(gridExtra)
library(kableExtra)
library(tidyr)
evals.scores <- evals %>%
  select(score, bty_avg)
model <- lm(score ~ bty_avg, data = evals.scores)
regression.points <- get_regression_points(model)
gapminder2007 <- gapminder %>%
  filter(year == 2007) %>% 
  select(country, continent, lifeExp)
lifeExp.model <- lm(lifeExp ~ continent, data = gapminder2007)
lifeExp.continent <- gapminder2007 %>%
  group_by(continent) %>%
  summarize(median = median(lifeExp), mean = mean(lifeExp))
lifeExp.by.continent <- gapminder2007 %>%
  group_by(continent) %>%
  summarize(median = median(lifeExp), mean = mean(lifeExp))
mean.africa <- lifeExp.by.continent %>%
  filter(continent == "Africa") %>%
  pull(mean)
regression_points <- get_regression_points(lifeExp.model)
```

# Introduction {-}

A vital part of data analysis is communicating the results of an analysis.  This usually takes the form or a report which summarizes the data analysis process and relevant findings.  There is a helpful guide to writing statistical reports following a statistical analysis in the **"Skills Tuesdays" Material** section of Moodle and you are expected to familiarize yourself with this resource, especially the sections on "Structure" and "Presentation". 

This week's tutorial introduces you to **R Markdown**, a very efficient way of producing statistical reports that you will use to produce reports in the two class tests and the group project in Data Analysis Skills.  You will also be required to use **R Markdown** to produce a report on your Masters Project in the summer.  

In this tutorial we will take what we have learned in previous weeks and produce a report using **R Markdown**. The package `rmarkdown` allows reports to be created within R, thus allowing for R code and output to be easily embedded within a report. Hence, all of the R code and plots obtained from an analysis are contained within a single file.

In this week's section on Moodle there is an **Example Report** produced using R Markdown relating to fitting a regression model using one numerical explanatory variable (we will consider fitting these models in more detail next week). The corresponding R Markdown file (`.Rmd`) can also be downloaded and opened in R to see how the document was produced (press the `Knit` button to create the PDF version). It is advised to have this document open within RStudio while working through the remaining sections in order to see examples put into practice.

The following sections will take you through the different steps required to produce the Example Report on Moodle. 

<br>
<br>

